LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := bulletc
LOCAL_C_INCLUDES := \
   $(LOCAL_PATH)/../../bullet-2.82-r2704/src \
   $(LOCAL_PATH)/../../bullet-2.82-r2704/src/BulletCollision/BroadphaseCollision \
   $(LOCAL_PATH)/../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch \
   $(LOCAL_PATH)/../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes \
   $(LOCAL_PATH)/../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision \
   $(LOCAL_PATH)/../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver \
   $(LOCAL_PATH)/../../bullet-2.82-r2704/src/BulletDynamics/Dynamics \
   $(LOCAL_PATH)/../../bullet-2.82-r2704/src/BulletDynamics/Vehicle \
   $(LOCAL_PATH)/../../bullet-2.82-r2704/src/LinearMath \
   $(LOCAL_PATH)/../../libbulletc/src


LOCAL_ARM_MODE := arm
LOCAL_CFLAGS := $(LOCAL_C_INCLUDES:%=-I%) -O3 -DANDROID_NDK
LOCAL_LDLIBS := -L$(SYSROOT)/usr/lib -ldl -llog

LOCAL_SRC_FILES := \
   ../../bullet-2.82-r2704/src/LinearMath/btVector3.cpp \
   ../../bullet-2.82-r2704/src/LinearMath/btPolarDecomposition.cpp \
   ../../bullet-2.82-r2704/src/LinearMath/btConvexHullComputer.cpp \
   ../../bullet-2.82-r2704/src/LinearMath/btConvexHull.cpp \
   ../../bullet-2.82-r2704/src/LinearMath/btAlignedAllocator.cpp \
   ../../bullet-2.82-r2704/src/LinearMath/btGeometryUtil.cpp \
   ../../bullet-2.82-r2704/src/LinearMath/btQuickprof.cpp \
   ../../bullet-2.82-r2704/src/LinearMath/btSerializer.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/BroadphaseCollision/btDispatcher.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/BroadphaseCollision/btDbvt.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btCollisionObject.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btManifoldResult.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btGhostObject.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btUnionFind.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btBoxShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btBox2dShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btCapsuleShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btCollisionShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btCompoundShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btConcaveShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btConeShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btConvex2dShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btConvexHullShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btConvexInternalShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btConvexShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btCylinderShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btEmptyShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btMultiSphereShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btOptimizedBvh.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btShapeHull.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btSphereShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btTetrahedronShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btTriangleBuffer.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btTriangleCallback.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btTriangleMesh.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/CollisionShapes/btUniformScalingShape.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp \
   ../../bullet-2.82-r2704/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/Vehicle/btRaycastVehicle.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/Vehicle/btWheelInfo.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btFixedConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btGearConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btContactConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/Dynamics/btRigidBody.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp \
   ../../bullet-2.82-r2704/src/BulletDynamics/Character/btKinematicCharacterController.cpp \
   ../../libbulletc/src/btWheelInfo_wrap.cpp \
   ../../libbulletc/src/btVoronoiSimplexSolver_wrap.cpp \
   ../../libbulletc/src/btUniversalConstraint_wrap.cpp \
   ../../libbulletc/src/btUniformScalingShape_wrap.cpp \
   ../../libbulletc/src/btTypedConstraint_wrap.cpp \
   ../../libbulletc/src/btTriangleMeshShape_wrap.cpp \
   ../../libbulletc/src/btTriangleMesh_wrap.cpp \
   ../../libbulletc/src/btTriangleIndexVertexArray_wrap.cpp \
   ../../libbulletc/src/btTransformUtil_wrap.cpp \
   ../../libbulletc/src/btStridingMeshInterface_wrap.cpp \
   ../../libbulletc/src/btStaticPlaneShape_wrap.cpp \
   ../../libbulletc/src/btSphereTriangleCollisionAlgorithm_wrap.cpp \
   ../../libbulletc/src/btSphereSphereCollisionAlgorithm_wrap.cpp \
   ../../libbulletc/src/btSphereShape_wrap.cpp \
   ../../libbulletc/src/btSphereBoxCollisionAlgorithm_wrap.cpp \
   ../../libbulletc/src/btSliderConstraint_wrap.cpp \
   ../../libbulletc/src/btSimulationIslandManager_wrap.cpp \
   ../../libbulletc/src/btShapeHull_wrap.cpp \
   ../../libbulletc/src/btSerializer_wrap.cpp \
   ../../libbulletc/src/btSequentialImpulseConstraintSolver_wrap.cpp \
   ../../libbulletc/src/btScaledBvhTriangleMeshShape_wrap.cpp \
   ../../libbulletc/src/btRigidBody_wrap.cpp \
   ../../libbulletc/src/btRaycastVehicle_wrap.cpp \
   ../../libbulletc/src/btPolyhedralConvexShape_wrap.cpp \
   ../../libbulletc/src/btPolarDecomposition_wrap.cpp \
   ../../libbulletc/src/btPointCollector_wrap.cpp \
   ../../libbulletc/src/btPoint2PointConstraint_wrap.cpp \
   ../../libbulletc/src/btPersistentManifold_wrap.cpp \
   ../../libbulletc/src/btOverlappingPairCallback_wrap.cpp \
   ../../libbulletc/src/btOverlappingPairCache_wrap.cpp \
   ../../libbulletc/src/btMultiSphereShape_wrap.cpp \
   ../../libbulletc/src/btMinkowskiPenetrationDepthSolver_wrap.cpp \
   ../../libbulletc/src/btManifoldPoint_wrap.cpp \
   ../../libbulletc/src/btKinematicCharacterController_wrap.cpp \
   ../../libbulletc/src/btHingeConstraint_wrap.cpp \
   ../../libbulletc/src/btHinge2Constraint_wrap.cpp \
   ../../libbulletc/src/btGjkPairDetector_wrap.cpp \
   ../../libbulletc/src/btGhostObject_wrap.cpp \
   ../../libbulletc/src/btGeometryUtil_wrap.cpp \
   ../../libbulletc/src/btGeneric6DofSpringConstraint_wrap.cpp \
   ../../libbulletc/src/btGeneric6DofConstraint_wrap.cpp \
   ../../libbulletc/src/btGearConstraint_wrap.cpp \
   ../../libbulletc/src/btFixedConstraint_wrap.cpp \
   ../../libbulletc/src/btEmptyCollisionAlgorithm_wrap.cpp \
   ../../libbulletc/src/btDynamicsWorld_wrap.cpp \
   ../../libbulletc/src/btDispatcher_wrap.cpp \
   ../../libbulletc/src/btDiscreteDynamicsWorld_wrap.cpp \
   ../../libbulletc/src/btDiscreteCollisionDetectorInterface_wrap.cpp \
   ../../libbulletc/src/btDefaultMotionState_wrap.cpp \
   ../../libbulletc/src/btDefaultCollisionConfiguration_wrap.cpp \
   ../../libbulletc/src/btDbvtBroadphase_wrap.cpp \
   ../../libbulletc/src/btCylinderShape_wrap.cpp \
   ../../libbulletc/src/btConvexTriangleMeshShape_wrap.cpp \
   ../../libbulletc/src/btConvexShape_wrap.cpp \
   ../../libbulletc/src/btConvexPolyhedron_wrap.cpp \
   ../../libbulletc/src/btConvexPlaneCollisionAlgorithm_wrap.cpp \
   ../../libbulletc/src/btConvexPenetrationDepthSolver_wrap.cpp \
   ../../libbulletc/src/btConvexInternalShape_wrap.cpp \
   ../../libbulletc/src/btConvexHullShape_wrap.cpp \
   ../../libbulletc/src/btConvexConvexAlgorithm_wrap.cpp \
   ../../libbulletc/src/btConvexConcaveCollisionAlgorithm_wrap.cpp \
   ../../libbulletc/src/btConvex2dShape_wrap.cpp \
   ../../libbulletc/src/btConvex2dConvex2dAlgorithm_wrap.cpp \
   ../../libbulletc/src/btContactSolverInfo_wrap.cpp \
   ../../libbulletc/src/btConstraintSolver_wrap.cpp \
   ../../libbulletc/src/btConeTwistConstraint_wrap.cpp \
   ../../libbulletc/src/btConeShape_wrap.cpp \
   ../../libbulletc/src/btCompoundShape_wrap.cpp \
   ../../libbulletc/src/btCompoundCompoundCollisionAlgorithm_wrap.cpp \
   ../../libbulletc/src/btCompoundCollisionAlgorithm_wrap.cpp \
   ../../libbulletc/src/btCollisionWorld_wrap.cpp \
   ../../libbulletc/src/btCollisionShape_wrap.cpp \
   ../../libbulletc/src/btCollisionObjectWrapper_wrap.cpp \
   ../../libbulletc/src/btCollisionObject_wrap.cpp \
   ../../libbulletc/src/btCollisionDispatcher_wrap.cpp \
   ../../libbulletc/src/btCollisionCreateFunc_wrap.cpp \
   ../../libbulletc/src/btCollisionConfiguration_wrap.cpp \
   ../../libbulletc/src/btCollisionAlgorithm_wrap.cpp \
   ../../libbulletc/src/btCharacterControllerInterface_wrap.cpp \
   ../../libbulletc/src/btCapsuleShape_wrap.cpp \
   ../../libbulletc/src/btBvhTriangleMeshShape_wrap.cpp \
   ../../libbulletc/src/btBroadphaseProxy_wrap.cpp \
   ../../libbulletc/src/btBroadphaseInterface_wrap.cpp \
   ../../libbulletc/src/btBoxShape_wrap.cpp \
   ../../libbulletc/src/btBoxCollision_wrap.cpp \
   ../../libbulletc/src/btBoxBoxCollisionAlgorithm_wrap.cpp \
   ../../libbulletc/src/btBox2dBox2dCollisionAlgorithm_wrap.cpp \
   ../../libbulletc/src/btAxisSweep3_wrap.cpp \
   ../../libbulletc/src/btAlignedManifoldArray_wrap.cpp \
   ../../libbulletc/src/btAlignedCollisionShapeArray_wrap.cpp \
   ../../libbulletc/src/btAlignedCollisionObjectArray_wrap.cpp \
   ../../libbulletc/src/btAlignedBroadphasePairArray_wrap.cpp \
   ../../libbulletc/src/btActionInterface_wrap.cpp \
   ../../libbulletc/src/SharpMotionState.cpp  \
   ../../libbulletc/src/btHeightfieldTerrainShape_wrap.cpp     

   include $(BUILD_SHARED_LIBRARY)